### ISSUE TITLE
APKTool called without file extension, not recognized as a command

### ISSUE THREAD

**Issue by leumasme** [rlxone/android-https-patcher#1]
I have added APKTool to the Path, however your python script tries to call it simply via 'apktool args' when it is actually a jar file.
This then logs 
```
'apktool' is not recognized as an internal or external command,
operable program or batch file.
```
Manually calling 'apktool.jar' via the command line from anywhere works, so i did successfully add it to the path.
Is this an issue on your side, or do i have to reconfigure something?

**Comment by rlxone** [comment]
Hi. As I remember from apktool installation guide, you need to add a wrapper script (apktool.bat for Windows) to your PATH. apktool.jar should be in the same folder.

https://ibotpeaches.github.io/Apktool/install/

Follow the guide, it worked for me both windows and macos while testing.

**Comment by leumasme** [comment]
Ah, yup. Adding a bat file to the PATH folder containing
`java -jar Y:\PathApps\apktool.jar %*`
fixes this problem. Thanks!
